### ISSUE TITLE
Error compiling cases with object definitions

### ISSUE THREAD

**Issue by jcallaham** [Nek5000/NekExamples#147]
Several cases that use defined objects seem to be not compiling. For example, the Taylor-Couette flow gives the error

`
Error: The function result on the lhs of the assignment at (1) must have the pointer attribute.  
`

There are similar issues with turbChannel, turbPipe, phill, ext_cyl, and vortex2.  It seems like maybe there was a change in core/bdry.f so that the boundaryID object is now called boundaryIDList.  This seems to fix the problem for me.  I'm new to Nek, but if someone else can confirm this would be a good fix I'm happy to take care of it.

**Comment by stgeke** [comment]
Are you using the latest Nek5000 master and NekExamples master?

On 27 Sep 2019, at 19:12, Jared Callaham <notifications@github.com <mailto:notifications@github.com> > wrote:

Several cases that use defined objects seem to be not compiling. For example, the Taylor-Couette flow gives the error

`taylor.f:222:12:


         boundaryID(3,iel) = 2
        1


Error: The function result on the lhs of the assignment at (1) must have the pointer attribute.
make: *** [nek5000] Error 1`

There are similar issues with turbChannel, turbPipe, phill, ext_cyl, and vortex2. It seems like maybe there was a change in core/bdry.f so that the boundaryID object is now called boundaryIDList. This seems to fix the problem for me. I'm new to Nek, but if someone else can confirm this would be a good fix I'm happy to take care of it.

**Comment by jcallaham** [comment]
No, I guess not.  I was using the v19.0-rc1 version from the releases page.  Looks like the master branch uses boundaryID instead of boundaryIDList.  Never mind!
