### ISSUE TITLE
modification of CylRestart tests

### ISSUE THREAD

**Issue by adampep** [Nek5000/NekExamples#41]
I would like to reorganize CylRestart tests. Right now we have 4 test ca, cb, pa, pb running independently pn-pn and pn-pn-2. It is not what one could expect, as ca should prepare restart files for cb, and pn-pn restart files differ with pn-pn-2 ones. So I would like to merge ca with cb and pa with pb. Is it ok?

**Comment by emerzari** [comment]
Hi Adam,

We discussed this last Tuesday with Aleks. Yes I think it would be preferable as I think right now they fail because there is no guarantee they will be done in sequence in Jenkins.

Best,

Elia


On Mar 16, 2017, at 6:53 AM, Adam Peplinski <notifications@github.com<mailto:notifications@github.com>> wrote:


I would like to reorganize CylRestart tests. Right now we have 4 test ca, cb, pa, pb running independently pn-pn and pn-pn-2. It is not what one could expect, as ca should prepare restart files for cb, and pn-pn restart files differ with pn-pn-2 ones. So I would like to merge ca with cb and pa with pb. Is it ok?

**Comment by stgeke** [comment]
With the right Jenkins config it should work.

On 16 Mar 2017, at 13:54, emerzari <notifications@github.com <mailto:notifications@github.com> > wrote:

Hi Adam,

We discussed this last Tuesday with Aleks. Yes I think it would be preferable as I think right now they fail because there is no guarantee they will be done in sequence in Jenkins.

Best,

Elia


On Mar 16, 2017, at 6:53 AM, Adam Peplinski <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> >> wrote:


I would like to reorganize CylRestart tests. Right now we have 4 test ca, cb, pa, pb running independently pn-pn and pn-pn-2. It is not what one could expect, as ca should prepare restart files for cb, and pn-pn restart files differ with pn-pn-2 ones. So I would like to merge ca with cb and pa with pb. Is it ok?

**Comment by RonRahaman** [comment]
Yes, this can be done, I believe.  I think we should make the changes in the nekTests.py script, rather than on Jenkins.  

The Python scripts define each test case as a compile/run/analyze sequence from start to finish.  Jenkins compiles/runs/analyzes each test case separately, from start to finish.  **The build and output data from previous test cases is not retained**.  This is the correct thing to do; it prevents tests from erroneously failing because of build or output data from previous test cases.

@adampep, do you want to compile/run/analyze ca, cb, pa, and pb in  and **retain the data from each test case**?

**Comment by adampep** [comment]
One of the reasons to combine ca with cb (and pa with pb) is to make tests that check one feature at the time. Right now ca, cb, pa, pb test the drag at given time and they will fail even with correct restart files (I've tested it) because there is some mismatch with reference value. However, we have ext_cyl test that check it, and cyl_restart should not repeat it. I guess in this case we should just test restart feature, so ca should provide restart files (proper one for pn-pn or pn-pn-2) and the reference value for cb. In the same test cb should use restart files and return the same drag as ca , and this should be the criteria of success. Not some arbitrary value from different simulation.

**Comment by RonRahaman** [comment]
Fixed in PR #63
